let string = 'welcome to node js';
let index = 2;
console.log(string.length);
console.log(string.includes('node'));
console.log(string.charAt(index));
console.log(string.at(index));
console.log(string.charCodeAt(index));
console.log(string.concat('& javascript'));
console.log(string.endsWith('js'));
console.log(string.indexOf('t'));
console.log(string.slice(3, 7));
console.log(string.startsWith('w'));
console.log(string.endsWith("js"));
console.log(string.toString());
console.log(string.toLowerCase());
console.log(string.toUpperCase());
console.log(string.trim());
console.log(string.toLocaleLowerCase());
// Number
console.log(Math.trunc(13.45));
console.log(Math.sqrt(9));
console.log(Math.round(0.9));
console.log(Math.pow(3, 2));
console.log(Math.min(2, 1));
console.log(Math.max(34, 89));
console.log(Math.ceil(.96));
console.log(Math.abs(45.78));